CREATE TABLE ClienToClientBank
(
  CLIENT_ID NUMERIC(5) NOT NULL,
  ClientID NUMERIC(5) NOT NULL,
  PRIMARY KEY (CLIENT_ID),
  FOREIGN KEY (ClientID) REFERENCES Client_Bank(ClientID),
  FOREIGN KEY (CLIENT_ID) REFERENCES Client(CLIENT_ID)  
);
